### ISSUE TITLE
Convert "Leitfaden Wissenschaftliches Arbeiten" to Quarto Book

### ISSUE THREAD

**Issue by klingelhoefer** [faucommsci/wissenschaftliches_arbeiten#4]
@chrdrn

**Comment by chrdrn** [comment]
- New branch [bookdown](https://github.com/faucommsci/wissenschaftliches_arbeiten/tree/bookdown) created
- [leitfaden_wissenschaftliches_arbeiten.qmd](https://github.com/faucommsci/wissenschaftliches_arbeiten/blob/main/leitfaden_wissenschaftliches_arbeiten.qmd) split into multiple chapters
- Further adjustments of the design necessary (@klingelhoefer)
